# Generated by Django 5.2.7 on 2025-11-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
