# Generated by Django 5.2.7 on 2025-11-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa/Patente'),
        ),
        migrations.AddField(
            model_name='auto',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
    ]
