# Generated by Django 5.2.7 on 2025-11-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_license_plate_auto_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='purchase_date',
        ),
    ]
