# Generated by Django 5.2.7 on 2025-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_userprofile_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
