# Generated by Django 5.2.7 on 2025-11-05 03:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_voicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('partial_count', models.PositiveIntegerField(default=0)),
                ('final_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CLOSED', 'Cerrada')], default='ACTIVE', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Sesión de Voz',
                'verbose_name_plural': 'Sesiones de Voz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceIngestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_key', models.CharField(max_length=128, unique=True)),
                ('start_ts', models.FloatField()),
                ('end_ts', models.FloatField()),
                ('transcript', models.TextField()),
                ('fields', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('watchdog', 'Watchdog (JSONL)'), ('realtime', 'Procesador en tiempo real')], default='watchdog', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingests', to='parts.voicesession')),
            ],
            options={
                'verbose_name': 'Resultado de Ingesta de Voz',
                'verbose_name_plural': 'Resultados de Ingesta de Voz',
                'indexes': [models.Index(fields=['-created_at'], name='parts_voice_created_667806_idx'), models.Index(fields=['pair_key'], name='parts_voice_pair_ke_78a4de_idx'), models.Index(fields=['session', '-created_at'], name='parts_voice_session_5f0616_idx')],
            },
        ),
    ]
