# Generated by Django 5.2.7 on 2025-11-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_part_image_reportschedule_reportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mic_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Micrófono',
                'verbose_name_plural': 'Configuraciones de Micrófono',
                'ordering': ['-updated_at'],
            },
        ),
    ]
