# Generated by Django 5.2.7 on 2025-11-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_micconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
