# Generated by Django 5.2.7 on 2025-11-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_perfilvozusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAILlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('chat', 'Chat'), ('whisper', 'Whisper'), ('tts', 'TTS'), ('otros', 'Otros')], max_length=16)),
                ('modelo', models.CharField(max_length=64)),
                ('tokens_prompt', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_respuesta', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('codigo_http', models.PositiveIntegerField(blank=True, null=True)),
                ('error_texto', models.TextField(blank=True, default='')),
                ('hash_prompt', models.CharField(blank=True, default='', max_length=64)),
                ('usuario_id', models.CharField(blank=True, default='', max_length=64)),
                ('origen', models.CharField(blank=True, default='', max_length=128)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Llamada OpenAI',
                'verbose_name_plural': 'Llamadas OpenAI',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='parts_opena_creado__dd18c4_idx'), models.Index(fields=['modelo'], name='parts_opena_modelo_00ae6b_idx'), models.Index(fields=['tipo'], name='parts_opena_tipo_409b57_idx')],
            },
        ),
    ]
