# Generated by Django 5.2.7 on 2025-11-08 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_openaillamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('partial', 'Parcial'), ('final', 'Final'), ('command', 'Comando')], default='partial', max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Transcripción de Voz',
                'verbose_name_plural': 'Transcripciones de Voz',
                'ordering': ['session_id', 'timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='parts_voice_session_bdd5e1_idx'), models.Index(fields=['session_id', 'type'], name='parts_voice_session_7ab04f_idx')],
            },
        ),
    ]
