# Generated by Django 5.2.7 on 2025-11-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_voicetranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='is_capturing',
            field=models.BooleanField(default=False, help_text='True durante un proceso activo de captura'),
        ),
        migrations.AddField(
            model_name='voicetranscription',
            name='is_capturing',
            field=models.BooleanField(db_index=True, default=False, help_text='True si se capturó durante un proceso activo'),
        ),
        migrations.AddIndex(
            model_name='voicetranscription',
            index=models.Index(fields=['session_id', 'is_capturing', 'type'], name='parts_voice_session_4ecc8a_idx'),
        ),
    ]
