# Generated by Django 5.2.7 on 2025-11-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_voicesession_is_capturing_and_more'),
    ]

    operations = [
    ]
