# Generated by Django 5.2.7 on 2025-11-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_add_is_capturing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceCommand',
        ),
    ]
