# Generated by Django 5.2.7 on 2025-11-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_part_barcode_eventosistema'),
    ]

    operations = [
    ]
