# Generated by Django 5.2.7 on 2025-11-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_voicesession_captura_iniciada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicesession',
            name='captura_iniciada',
        ),
        migrations.RemoveField(
            model_name='voicesession',
            name='esperando_confirmacion',
        ),
        migrations.RemoveField(
            model_name='voicesession',
            name='grabacion_finalizada',
        ),
        migrations.AddField(
            model_name='voicesession',
            name='estado_grabacion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Iniciado'), (2, 'Finalizado'), (3, 'Esperando confirmación')], db_index=True, default=0, help_text='Ciclo de captura: 0 Inactivo, 1 Iniciado, 2 Finalizado, 3 Esperando confirmación'),
        ),
    ]
