# Generated by Django 5.2.7 on 2025-10-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('max_value', models.PositiveIntegerField(default=0)),
                ('min_value', models.PositiveIntegerField(default=0)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.auto')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.workshop')),
            ],
        ),
    ]
