# Generated by Django 5.2.7 on 2025-11-11 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_delete_voicecommand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras único generado automáticamente', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('categoria', models.CharField(choices=[('pieza', 'Pieza'), ('barcode', 'Código de Barras'), ('voz', 'Voz'), ('usuario', 'Usuario'), ('sistema', 'Sistema'), ('error', 'Error'), ('api_externa', 'API Externa'), ('impresion', 'Impresión')], db_index=True, max_length=20)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('accion', models.CharField(help_text='Acción realizada (crear_pieza, generar_barcode, etc.)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada del evento')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Datos contextuales del evento')),
                ('exito', models.BooleanField(default=True)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('duracion_ms', models.PositiveIntegerField(blank=True, help_text='Duración de la operación en ms', null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', help_text='ID de request HTTP para correlacionar eventos', max_length=64)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='parts.part')),
                ('sesion_voz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='parts.voicesession')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'categoria'], name='parts_event_timesta_00f438_idx'), models.Index(fields=['-timestamp', 'nivel'], name='parts_event_timesta_891207_idx'), models.Index(fields=['request_id'], name='parts_event_request_4b6dcb_idx'), models.Index(fields=['usuario', '-timestamp'], name='parts_event_usuario_d8930f_idx'), models.Index(fields=['pieza', '-timestamp'], name='parts_event_pieza_i_0270fc_idx'), models.Index(fields=['exito', '-timestamp'], name='parts_event_exito_968234_idx')],
            },
        ),
    ]
