# Generated by Django 5.2.7 on 2025-11-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_add_barcode_and_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='captura_iniciada',
            field=models.BooleanField(default=False, help_text="Se detectó 'iniciar proceso'"),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='esperando_confirmacion',
            field=models.BooleanField(default=False, help_text="Esperando 'confirmar datos' del usuario"),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='grabacion_finalizada',
            field=models.BooleanField(default=False, help_text="Se detectó 'finalizar/terminar/detener proceso'"),
        ),
    ]
