# Generated by Django 5.2.7 on 2025-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_partphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
