# Generated by Django 5.2.7 on 2025-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_alter_partphoto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Notas'),
        ),
    ]
