# Generated by Django 5.2.7 on 2025-11-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_auto_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(db_index=True, max_length=100)),
                ('severidad', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=16)),
                ('descripcion', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='eventosistema',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID para agrupar eventos correlacionados', max_length=64),
        ),
        migrations.AddField(
            model_name='eventosistema',
            name='hash_actual',
            field=models.CharField(blank=True, default='', help_text='Hash SHA256 del evento actual', max_length=64),
        ),
        migrations.AddField(
            model_name='eventosistema',
            name='hash_previo',
            field=models.CharField(blank=True, default='', help_text='Hash del evento anterior en la cadena', max_length=64),
        ),
        migrations.AddField(
            model_name='eventosistema',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subeventos', to='parts.eventosistema'),
        ),
        migrations.AddIndex(
            model_name='eventosistema',
            index=models.Index(fields=['correlation_id', '-timestamp'], name='parts_event_correla_072715_idx'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_aceptadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='parts.eventosistema'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['-creada_en', 'tipo'], name='parts_alert_creada__36fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['severidad', '-creada_en'], name='parts_alert_severid_6d1ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['correlation_id'], name='parts_alert_correla_46ea3e_idx'),
        ),
    ]
