# Generated by Django 5.2.7 on 2025-11-24 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_alertasistema_eventosistema_correlation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_fuente', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('manual', 'Manual'), ('api', 'API')], default='excel', max_length=20)),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo importado', max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta completa del archivo', max_length=500)),
                ('fecha_creacion_archivo', models.DateTimeField(blank=True, help_text='Fecha de creación del Excel según metadata', null=True)),
                ('fecha_modificacion_archivo', models.DateTimeField(blank=True, help_text='Última modificación del Excel según metadata', null=True)),
                ('autor_archivo', models.CharField(blank=True, help_text='Autor del archivo según metadata', max_length=200)),
                ('total_filas_procesadas', models.PositiveIntegerField(default=0)),
                ('filas_exitosas', models.PositiveIntegerField(default=0)),
                ('filas_con_errores', models.PositiveIntegerField(default=0)),
                ('filas_con_warnings', models.PositiveIntegerField(default=0)),
                ('total_correcciones_ortografia', models.PositiveIntegerField(default=0)),
                ('total_posiciones_extraidas', models.PositiveIntegerField(default=0)),
                ('total_nombres_persona_detectados', models.PositiveIntegerField(default=0)),
                ('total_estados_anomalos', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('revertida', 'Revertida')], default='en_proceso', max_length=20)),
                ('duracion_segundos', models.FloatField(blank=True, help_text='Duración del proceso en segundos', null=True)),
                ('log_resumen', models.TextField(blank=True, help_text='Resumen del proceso de importación')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de errores encontrados')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Lista de advertencias')),
                ('estadisticas', models.JSONField(blank=True, default=dict, help_text='Estadísticas detalladas de la importación')),
                ('archivo_reporte', models.FileField(blank=True, help_text='Reporte JSON/PDF de la importación', null=True, upload_to='importaciones/reportes/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Inventario',
                'verbose_name_plural': 'Importaciones de Inventario',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionOrtografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_original', models.CharField(db_index=True, max_length=100)),
                ('palabra_corregida', models.CharField(max_length=100)),
                ('frecuencia', models.PositiveIntegerField(default=0, help_text='Cuántas veces se encontró este error')),
                ('ejemplos', models.JSONField(blank=True, default=list, help_text='Ejemplos de textos donde apareció el error')),
                ('fecha_primera_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_deteccion', models.DateTimeField(auto_now=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='parts.importacioninventario')),
            ],
            options={
                'verbose_name': 'Corrección Ortográfica',
                'verbose_name_plural': 'Correcciones Ortográficas',
                'ordering': ['-frecuencia', 'palabra_original'],
            },
        ),
        migrations.CreateModel(
            name='PiezaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.TextField(help_text='Nombre exacto como viene en el Excel')),
                ('nombre_normalizado', models.CharField(db_index=True, help_text='Nombre normalizado (sin posiciones, corregido)', max_length=200)),
                ('posicion', models.CharField(blank=True, help_text='Posición extraída (Izquierda/Derecha, Delantera/Trasera, etc)', max_length=100)),
                ('stock', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Vendido'), ('NO DISPONIBLE', 'No Disponible'), ('POR CONFIRMAR', 'Por Confirmar'), ('CONFIRMAR', 'Confirmar')], default='DISPONIBLE', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del repuesto', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio actual de venta', max_digits=10)),
                ('ultimo_precio', models.DecimalField(decimal_places=2, default=0, help_text='Último precio registrado (histórico)', max_digits=10)),
                ('venta', models.CharField(blank=True, help_text='Información de venta si aplica', max_length=200)),
                ('nota', models.TextField(blank=True, help_text='Notas adicionales del Excel')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones automáticas: errores detectados, warnings, etc')),
                ('tiene_errores_ortografia', models.BooleanField(default=False)),
                ('tiene_nombre_persona', models.BooleanField(default=False)),
                ('tiene_estado_anomalo', models.BooleanField(default=False)),
                ('tiene_precio_anomalo', models.BooleanField(default=False)),
                ('sin_ubicacion', models.BooleanField(default=False)),
                ('es_multiple_piezas', models.BooleanField(default=False, help_text='JUEGO, KIT, PAR detectado')),
                ('calidad_datos', models.PositiveSmallIntegerField(default=100, help_text='Calidad de 0-100 según anomalías detectadas')),
                ('requiere_revision', models.BooleanField(db_index=True, default=False, help_text='Marcado para revisión manual')),
                ('revisado', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(db_index=True, default=False, help_text='True si ya se creó/actualizó un Part correspondiente')),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingesta_excel', models.DateTimeField(blank=True, help_text='Fecha aproximada cuando se ingresó en el Excel', null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('hash_contenido', models.CharField(blank=True, db_index=True, help_text='SHA256 de campos clave para detectar duplicados', max_length=64)),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_importadas', to='parts.importacioninventario')),
                ('part_relacionado', models.ForeignKey(blank=True, help_text='Part en sistema si ya se sincronizó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='parts.part')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pieza de Inventario',
                'verbose_name_plural': 'Piezas de Inventario',
                'ordering': ['vehiculo', 'nombre_normalizado'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nombre_persona', 'Nombre de Persona'), ('estado_anomalo', 'Estado Anómalo'), ('precio_invalido', 'Precio Inválido'), ('sin_ubicacion', 'Sin Ubicación'), ('duplicado', 'Duplicado'), ('texto_duplicado', 'Texto Duplicado (DE DE)'), ('multiple_piezas', 'Múltiples Piezas'), ('inconsistencia', 'Inconsistencia de Datos')], db_index=True, max_length=30)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la anomalía')),
                ('valor_detectado', models.CharField(blank=True, help_text='Valor que causó la anomalía', max_length=200)),
                ('campo_afectado', models.CharField(blank=True, help_text='Campo donde se detectó (nombre, precio, etc)', max_length=50)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_resueltas', to=settings.AUTH_USER_MODEL)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='parts.importacioninventario')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='parts.piezainventario')),
            ],
            options={
                'verbose_name': 'Anomalía de Inventario',
                'verbose_name_plural': 'Anomalías de Inventario',
                'ordering': ['-severidad', '-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre del vehículo (ej: 116I 2006, OTROS, NEW SAIL 2021)', max_length=100, unique=True)),
                ('marca_modelo', models.CharField(blank=True, help_text='Marca y modelo extraído del nombre', max_length=100)),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Año del vehículo si se puede extraer', null=True)),
                ('fecha_primera_importacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_piezas', models.PositiveIntegerField(default=0)),
                ('piezas_disponibles', models.PositiveIntegerField(default=0)),
                ('piezas_vendidas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el vehículo fuente')),
                ('auto_relacionado', models.ForeignKey(blank=True, help_text='Auto en sistema si existe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='parts.auto')),
            ],
            options={
                'verbose_name': 'Vehículo de Inventario',
                'verbose_name_plural': 'Vehículos de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='piezainventario',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_inventario', to='parts.vehiculoinventario'),
        ),
        migrations.AddIndex(
            model_name='importacioninventario',
            index=models.Index(fields=['-fecha_importacion', 'estado'], name='parts_impor_fecha_i_d02e64_idx'),
        ),
        migrations.AddIndex(
            model_name='importacioninventario',
            index=models.Index(fields=['usuario', '-fecha_importacion'], name='parts_impor_usuario_cbecbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correccionortografica',
            unique_together={('importacion', 'palabra_original')},
        ),
        migrations.AddIndex(
            model_name='anomaliainventario',
            index=models.Index(fields=['tipo', 'resuelta'], name='parts_anoma_tipo_0096ed_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaliainventario',
            index=models.Index(fields=['severidad', '-fecha_deteccion'], name='parts_anoma_severid_040b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaliainventario',
            index=models.Index(fields=['pieza', 'tipo'], name='parts_anoma_pieza_i_99e29b_idx'),
        ),
        migrations.AddIndex(
            model_name='piezainventario',
            index=models.Index(fields=['vehiculo', 'stock'], name='parts_pieza_vehicul_e070eb_idx'),
        ),
        migrations.AddIndex(
            model_name='piezainventario',
            index=models.Index(fields=['stock', 'sincronizado'], name='parts_pieza_stock_b65b37_idx'),
        ),
        migrations.AddIndex(
            model_name='piezainventario',
            index=models.Index(fields=['requiere_revision', '-calidad_datos'], name='parts_pieza_requier_1e2e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='piezainventario',
            index=models.Index(fields=['sincronizado', 'fecha_importacion'], name='parts_pieza_sincron_55f6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='piezainventario',
            index=models.Index(fields=['hash_contenido'], name='parts_pieza_hash_co_56965d_idx'),
        ),
    ]
