# Generated by Django 5.2.7 on 2025-11-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_uppercase_part_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('part', 'Pieza'), ('position', 'Posición'), ('state', 'Estado'), ('generic', 'Genérico')], default='part', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SynonymTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('normalized_term', models.CharField(db_index=True, editable=False, max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Menor valor = mayor prioridad')),
                ('locale', models.CharField(blank=True, default='', help_text='Región/idioma opcional', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='parts.synonymgroup')),
            ],
            options={
                'ordering': ['group', 'priority', 'term'],
                'indexes': [models.Index(fields=['normalized_term'], name='parts_synon_normali_f8c24b_idx'), models.Index(fields=['group', 'priority'], name='parts_synon_group_i_71f396_idx')],
                'unique_together': {('group', 'term')},
            },
        ),
    ]
