# Generated by Django 5.2.7 on 2025-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_seed_initial_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
