# Generated by Django 5.2.7 on 2025-12-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0033_alter_part_price_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('codigo_escaneado', models.CharField(help_text='Código de barras leído por el escáner', max_length=100)),
                ('formato_codigo', models.CharField(blank=True, default='', help_text='Formato del código (EAN_13, CODE_128, etc.)', max_length=50)),
                ('codigo_esperado', models.CharField(blank=True, default='', help_text='Código de barras que se esperaba encontrar', max_length=100)),
                ('resultado', models.CharField(choices=[('match', 'Coincide'), ('mismatch', 'No coincide'), ('not_found', 'Código no encontrado'), ('scan_only', 'Solo escaneo (sin pieza seleccionada)')], db_index=True, max_length=20)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('pieza_buscada', models.ForeignKey(blank=True, help_text='Pieza que el usuario buscaba', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_buscada', to='parts.part')),
                ('pieza_encontrada', models.ForeignKey(blank=True, help_text='Pieza cuyo código coincide con el escaneado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_encontrada', to='parts.part')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Inventario',
                'verbose_name_plural': 'Verificaciones de Inventario',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'resultado'], name='parts_verif_timesta_18f9cc_idx'), models.Index(fields=['codigo_escaneado'], name='parts_verif_codigo__c54efd_idx')],
            },
        ),
    ]
