"""
Django settings for car_inventory project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from logging.config import dictConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dlqt!)6jey7e!6d$w-kdc(haol$ry-#^(1@#!50()#&qskm%2e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Trust proxy headers from Cloudflare/NGINX
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
# Character encoding settings
DEFAULT_CHARSET = 'utf-8'

# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',  # WebSocket support
    'rest_framework',  # Django REST Framework
    'rest_framework.authtoken',  # Token authentication
    'drf_spectacular',  # API documentation
    'corsheaders',  # CORS headers
    'parts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos en producción
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (debe ir antes de CommonMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'parts.middleware.AjaxErrorMiddleware',  # Convierte errores a JSON para AJAX
]

ROOT_URLCONF = 'car_inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'car_inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Tiempo de espera ante bloqueos (segundos)
            'timeout': 20,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/parts/'
LOGOUT_REDIRECT_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'parts' / 'static']

# WhiteNoise configuration for production static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------
# Logging estructurado (Opción A: JSON por línea) con rotación

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'fmt': '%(asctime)s %(levelname)s %(name)s %(message)s %(module)s %(process)d %(thread)d',
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'app.jsonl'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'json',
            'level': 'INFO',
        },
        'voice_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'voice.jsonl'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'json',
            'level': 'INFO',
        },
        'bluetooth_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'bluetooth.jsonl'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'json',
            'level': 'INFO',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'parts': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'parts.voice': {
            'handlers': ['console', 'voice_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'parts.bluetooth': {
            'handlers': ['console', 'app_file', 'bluetooth_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'app_file'],
        'level': 'WARNING'
    }
}

# Development helper: toggle Windows-mode for external binaries
# When WINDOWS_MODE = True the views will attempt to use the paths
# defined in WINDOWS_PATHS (useful to test on Windows). When False the
# original unix-style hardcoded paths are used.
# NOTE: This is intended for quick local testing only.
WINDOWS_MODE = os.environ.get('WINDOWS_MODE', 'True') == 'True'

# Provide default suggestions here; please update these paths to match
# your local installation if you enable WINDOWS_MODE.
WINDOWS_PATHS = {
    # Example path to whisper-cli binary on Windows (update as needed)
    'whisper_bin': r"C:\\Tools\\whisper_cpp\\Release\\whisper-cli.exe",
    # Example model path for ggml model (we downloaded ggml-medium.bin)
    'model_path': r"C:\\Tools\\whisper_cpp\\models\\ggml-medium.bin",
}

# OpenAI API configuration (for GPT-4o)
# Get your API key from https://platform.openai.com/api-keys
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", None)

# Voice normalization strategy
# Prefer delegating artifact correction to the LLM; also enable manual rules as a safety net
VOICE_NORMALIZE_WITH_LLM = True
VOICE_MANUAL_NORMALIZATION = True
VOICE_TRANSCRIPCION_VOSK_ACTIVA = os.environ.get('VOSK_TRANSCRIPCION_ACTIVA', 'false').lower() == 'true'

# ------------------------------------------------------------------
# Channels/WebSocket Configuration

ASGI_APPLICATION = 'car_inventory.asgi.application'

# Configuración de Redis para Channels
# Soporta REDIS_URL (formato: redis://host:port/db) como primera opción
# o REDIS_HOST con puerto por defecto 6379
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    # Usar REDIS_URL directamente (formato: redis://host:port/db)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Fallback a REDIS_HOST y puerto por defecto
    REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
    REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_HOST, REDIS_PORT)],
            },
        },
    }

# ------------------------------------------------------------------
# Django REST Framework Configuration

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# drf-spectacular Settings (API Documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Car Inventory API',
    'DESCRIPTION': 'API REST para gestión de inventario de autopartes. Incluye endpoints para piezas, talleres, autos y reportes.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# CORS Configuration (permitir acceso desde frontend)
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:8000'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# ------------------------------------------------------------------
# Security Settings for Production
# These will be automatically enabled when DEBUG=False

if not DEBUG:
    # HTTPS/SSL - Enabled with Let's Encrypt SSL certificate
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
    SESSION_COOKIE_SECURE = True  # Cookies only over HTTPS
    CSRF_COOKIE_SECURE = True  # CSRF cookies over HTTPS
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    # Permitir iframes del mismo origen para preview de reportes PDF
    X_FRAME_OPTIONS = 'SAMEORIGIN'
