# Generated by Django 5.2.7 on 2025-10-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MODELO_AUTO',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TALLER',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=100)),
                ('dirrecion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='REPUESTO',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_repuesto', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fec_ingreso', models.DateField(blank=True)),
                ('fec_venta', models.DateField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.estado')),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.modelo_auto')),
                ('id_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.taller')),
            ],
        ),
    ]
