# Generated by Django 5.2.7 on 2025-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='posicion',
            field=models.CharField(default='Unico', max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ultimo_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
