# Generated by Django 5.2.7 on 2025-10-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_repuesto_posicion_repuesto_ultimo_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSICION',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='posicion',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='id_posicion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='repuestos.posicion'),
            preserve_default=False,
        ),
    ]
