# Generated by Django 5.2.7 on 2025-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0003_posicion_remove_repuesto_posicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='fec_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='fec_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
